hasGeneratedWorlds: false
jsonlog: "../socket"
logMessagesBlacklist:
  - "[Matrix] Enabling Matrix"
  - "[Matrix] Disabling Matrix"
  - "[Matrix] Loading Matrix"
logMessagesOfInterest:
  - "too quickly"
  - "[Matrix]"
  - "issued server command:"
  - "overloaded"
worlds:
  # mesa
  world1:
    # the better seed is in a comment
    path: "world1"
    # -671686628
    seed: 102043410
    gameSettings:
      worldBorder:
        finalDistance: 5
      timeConfig:
        startDistanceTime: 90
        wborderShrinkPart2: 150
        roundEnd: 180
      gamePointsToAward: 2

  # plains
  world2:
    path: "world2"
    seed: 1164102382
    # 1248421

  # jungle
  world3:
    path: "world3"
    seed: -888289981
    # -400391389

  # ice spike
  world4:
    path: "world4"
    seed: 527517686
    # -1766999811

  # island
  world5:
    path: "world5"
    seed: 1337420
    # -1712572161

  # jungle amplified
  world6:
    path: "world6"
    seed: -888289981
    generator: AMPLIFIED
    # -400391389

  # extreme hills AMPLIFIED
  world7:
    path: "world7"
    seed: -141571315
    # 2070558
    generator: AMPLIFIED
gameSettings:
  gamePointsToAward: 1
  numWorlds: 7
  numLootChests: 500
  healthRegen: 2
  points:
    normal: 100
    bonus:
      killingSomeoneWhoHasMorePoints: 50
    lootChestOpen: 10
    airdropOpen: 40
  worldBorder:
    startDistance: 2500
    secondDistance: 500
    finalDistance: 50
  timeConfig:
    startDistanceTime: 900
    wborderShrinkPart2: 1500
    roundEnd: 1800
probability:
  # 1/n
  airdrop: 60
state:
  currentRound: 0
  isInProgress: false
  inventoriesToClear:
    -
  playerData:
    notarealuid:
      regenHealth: true
      isDead: false
      points: 10
      gamePoints: 1