worlds:
  # mesa
  world1:
    path: "world1"
    seed: 0
  # plains
  world2:
    path: "world2"
    seed: 0
  # bamboo jungle
  world3:
    path: "world3"
    seed: 0
  # forest
  world4:
    path: "world4"
    seed: 0
  # sky island
  world5:
    path: "world5"
    seed: 0
    enviornment: THE_END
  # cave world
  world6:
    path: "world6"
    seed: 0
    enviornment: NETHER
  # extreme hills AMPLIFIED
  world7:
    path: "world7"
    seed: 0
    generatorName: ampliflied

