jsonlog: "../socket"
logMessagesBlacklist:
  - "[Matrix] Enabling Matrix"
  - "[Matrix] Disabling Matrix"
  - "[Matrix] Loading Matrix"
logMessagesOfInterest:
  - "too quickly"
  - "[Matrix]"
  - "issued server command:"
  - "overloaded"
worlds:
  # mesa
  world1:
    path: "world1"
    seed: 102043410
  # plains
  world2:
    path: "world2"
    seed: 1164102382
  # jungle
  world3:
    path: "world3"
    seed: -400391389
  # ice spike
  world4:
    path: "world4"
    seed: -1766999811
  # sky island
  world5:
    path: "world5"
    seed: 1337420
    enviornment: THE_END
  # island
  world6:
    path: "world6"
    seed: -1712572161
  # extreme hills AMPLIFIED
  world7:
    path: "world7"
    seed: 2070558
    generatorName: ampliflied
worldBorder:
  startDistance: 2500
  startDistanceTime: 500
  secondDistance: 500
  finalDistance: 250
timeConfig:
  wborderShrinkPart2: 750
  roundEnd: 1000
gameSettings:
  # isInProgress: false#
  # currentRound: 0#
  numLootChests: 40
  healthRegen: 2
  points:
    normal: 10
probability:
  # 1/n
  airdrop: 60
state:
  currentRound: 0
  isInProgress: false
  inventoriesToClear:
    -
  playerData:
    notarealuid:
      regenHealth: true
      isDead: false
      points: 10
      gamePoints: 1