name: MinecraftRoyale
main: tk.minecraftroyale.MinecraftRoyale
version: 1.0-SNAPSHOT
commands:
  enabledevcommands:
    description: Enables the use of development / debugging commands.
    usage: /enabledevcommands
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - enabledev
      - ed
      - edc
  loadworld:
    description: Loads (or creates) a world with the given round number.
    usage: /loadworld [round]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - lw
