name: MinecraftRoyale
main: tk.minecraftroyale.MinecraftRoyale
version: 1.0-SNAPSHOT
commands:
  toggledevcommands:
    description: Enables the use of development / debugging commands.
    usage: /toggledevcommands
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - devcommands
      - devcmds
  loadworld:
    description: Loads (or creates) a world with the given round number.
    usage: /loadworld [round]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - lw
  mrtp:
    description: Teleports you to the spawn point of a world.
    usage: /mrtp [worldname | roundnumber]
    permission: mr.tp
    permission-message: You do not have permission to do this.
  createworld:
    description: Creates a world
    usage: /createworld [roundnumber]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  setupwborder:
    description: Sets the world border
    usage: /setupwborder [roundnumber]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  addloottables:
    description: Adds the loot tables to this world.
    usage: /addloottables
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
