name: MinecraftRoyale
main: tk.minecraftroyale.MinecraftRoyale
version: 1.0-SNAPSHOT
api-version: "1.13"
commands:
  toggledevcommands:
    description: Enables the use of development / debugging commands.
    usage: /toggledevcommands
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - devcommands
      - devcmds
  loadworld:
    description: Loads (or creates) a world with the given round number.
    usage: /loadworld [round]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - lw
  mrtp:
    description: Teleports you to the spawn point of a world.
    usage: /mrtp [worldname | roundnumber]
    permission: mr.tp
    permission-message: You do not have permission to do this.
  createworld:
    description: Creates a world
    usage: /createworld [roundnumber]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  setupwborder:
    description: Sets the world border
    usage: /setupwborder [roundnumber]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  installloottables:
    description: Adds the loot tables to this world.
    usage: /addloottables
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
    aliases:
      - instloot
      - addloottables
  airdrop:
    description: Airdrops at the specified coordinates (0, 0 default)
    usage: /airdrop <x z>
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  addlootchest:
    description: Makes a loot chest.
    usage: /addlootchest
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  addlootchests:
    description: Makes a loot chest.
    usage: /addlootchests [num]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  resetconfig:
    description: Resets plugin config
    usage: /resetconfig
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  endround:
    description: Ends the round
    usage: /endround
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  randomtp:
    description: Teleports you randomly
    usage: /randomtp
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  dopostworldgenstuff:
    description: Run post-worldgen stuff (worldborder, l00t chests, etc.)
    usage: /dopostworldgenstuff
    aliases:
      - roundenable
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  getpoints:
    description: Returns the points a player has.
    usage: /getpoints <player>
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  unkill:
    description: Allows a player to join a round they have already died in.
    usage: /unkill [player]
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  setpoints:
    description: Sets the points a player has.
    usage: /setpoints [points] <player>
    permission: wb.dev
    permission-message: You do not have permission to use development commands.
  getwborder:
    description: Get the current size of the world border. Note that this is a measurement of the width of the border, NOT its distance from (0, 0)
    usage: /getwborder
    permission: getwborder
    permission-message: You do not have permission to get the world border.
    aliases:
      - getworldborder
      - wbordersize
      - worldbordersize
      - wborder
permissions:
  getwborder:
    description: Allows you to get the world border.
    default: true

